import "./globals.css";
import Header from "@/components/header";

// remote font import
import { Montserrat } from "next/font/google";

// remote font kurulumu
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["400", "500", "600", "700", "800", "900"],
});

// local font import
import LocalFont from "next/font/local";

// local font kurulumuü
const mistery = LocalFont({
  src: "../assets/mistery.otf",
  variable: "--font-mistery",
  weight: "100 700",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${montserrat.variable} ${mistery.variable}`}
      >
        <Header />
        <div className="text-center text-2xl font-semibold">{children}</div>
      </body>
    </html>
  );
}
